//
//  ProfileCoordinator.swift
//  ReMVVMExample
//
//  Created by Grzegorz Jurzak on 27/01/2020.
//  Copyright © 2020 MOBIGREG. All rights reserved.
//

import ReMVVM
import ReMVVMExt
import RxSwift

struct TestMiddleware: Middleware {

    typealias Action = StoreAction
    typealias State = ApplicationState

    func onNext(for state: State, action: Action, interceptor: Interceptor<Action, State>, dispatcher: Dispatcher) {
        interceptor.next()
    }

}

class ProfileCoordinator {

    public static func createMiddlewares() -> [AnyMiddleware] {
        return [
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,
            TestMiddleware().any,

            ShowLoginActionHandler().any,
            ShowProfileActionHandler().any,
        ]
    }

    private let dispatcher: Dispatcher
    private let disposeBag = DisposeBag()

    init(dispatcher: Dispatcher) {
        self.dispatcher = dispatcher
    }

}
